// <auto-generated />
using System;
using InfotavleBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfotavleBackend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfotavleBackend.Entities.CalendarEvents", b =>
                {
                    b.Property<int>("eventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eventID"));

                    b.Property<int?>("slideID")
                        .HasColumnType("int");

                    b.Property<DateTime>("theDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("theMessage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("eventID");

                    b.HasIndex("slideID");

                    b.ToTable("calendarEvents");
                });

            modelBuilder.Entity("InfotavleBackend.Entities.Slides", b =>
                {
                    b.Property<int>("slidesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slidesID"));

                    b.Property<string>("componentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("expirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.HasKey("slidesID");

                    b.ToTable("slides");
                });

            modelBuilder.Entity("InfotavleBackend.Entities.TheComments", b =>
                {
                    b.Property<int>("commentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentsID"));

                    b.Property<string>("commentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("commentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("commentsID");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("InfotavleBackend.Entities.CalendarEvents", b =>
                {
                    b.HasOne("InfotavleBackend.Entities.Slides", "theSlides")
                        .WithMany()
                        .HasForeignKey("slideID");

                    b.Navigation("theSlides");
                });
#pragma warning restore 612, 618
        }
    }
}
